### PR TITLE
Angular 17 moment adapter

### PR DESCRIPTION
**Pull request by pavlikxor**

### CODE REVIEW

**Review by neodescis — COMMENTED** [review]
Shouldn't we update the tsconfig files here like you did in the dayjs adapter?

**Review by EricMallard — APPROVED** [review]

**Comment by sabareeshnarayanaswamy** [comment]
Could you please let know when this PR will be merged and officially released ?

**Comment by danielmoncada** [comment]
> Shouldn't we update the tsconfig files here like you did in the dayjs adapter?

im not even sure why some of the changes were made on the dayjs adapter (regarding the config). this pr has bare minimum updates (which I prefer). I've fixed a few things with it, and was able to package it.

going to release it now, as is. is there anything in particular you want changed to it? i can do a patch release if so.

**Comment by danielmoncada** [comment]
> Could you please let know when this PR will be merged and officially released ?

@sabareeshnarayanaswamy this has been released, v4.0.0

**Comment by neodescis** [comment]
> > Shouldn't we update the tsconfig files here like you did in the dayjs adapter?
> 
> @neodescis
> 
> im not even sure why some of the changes were made on the dayjs adapter (regarding the config). this pr has bare minimum updates (which I prefer). I've fixed a few things with it, and was able to package it.
> 
> going to release it now, as is. is there anything in particular you want changed to it? i can do a patch release if so.
> 
> sidenote: appreciate you helping out, leaving comments, and doing code reviews. admittedly, I haven't had enough time for this, especially since I've moved on to Vue (for my day job).

Happy to help out. We've actually been considering creating a (private) fork of this (for my day job), but meanwhile I have a vested interest in seeing it updated!

As for the tsconfig changes, the PR for dayjs has changes that restructure the tsconfig files like a new Angular 17 project. The structure of the tsconfig files in this repo is no longer current. It's not harming anything per se though.

**Comment by danielmoncada** [comment]
> > > Shouldn't we update the tsconfig files here like you did in the dayjs adapter?
> > 
> > 
> > @neodescis
> > im not even sure why some of the changes were made on the dayjs adapter (regarding the config). this pr has bare minimum updates (which I prefer). I've fixed a few things with it, and was able to package it.
> > going to release it now, as is. is there anything in particular you want changed to it? i can do a patch release if so.
> > sidenote: appreciate you helping out, leaving comments, and doing code reviews. admittedly, I haven't had enough time for this, especially since I've moved on to Vue (for my day job).
> 
> Happy to help out. We've actually been considering creating a (private) fork of this (for my day job), but meanwhile I have a vested interest in seeing it updated!
> 
> As for the tsconfig changes, the PR for dayjs has changes that restructure the tsconfig files like a new Angular 17 project. The structure of the tsconfig files in this repo is no longer current. It's not harming anything per se though.

Ah, that makes sense.

I mean, feel free to make a PR if ya want to adhere to the new ng 17 config format. I think the moment adapter didnt build for me, I'll review and test again as I see there are new changes.

**Pull request merged**
